In [25]:
# Import pytorch
import torch

In [26]:
# Sigmoid Activation Function

def activation(x):
    """
    Sigmoid Activation function
    
    Arguments:
    x: torch.Tensor
    """
    
    return 1/(1+torch.exp(-x))

In [27]:

## Generate Data
torch.manual_seed(7) #set random seed

#input features | create tensor of 1 row & 5 columns
features = torch.randn((1,5))

# Weights | create tensor with same shape
weights = torch.randn_like(features)

# Bias | 1 row & 1 column
bias = torch.randn((1,1))



In [28]:
# make labels from our data and true weights
y = activation(torch.sum(features * weights)+bias)
print(y)
# Or use sum method
y = activation((features * weights).sum() + bias)
print(y)

tensor([[0.1595]])
tensor([[0.1595]])


In [29]:
# Matrix Multiplication in Torch
# Accelerated with Cuda n GPU
#torch.matlul less strict

torch.mm(features,weights)


RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:752

In [30]:
weights.shape

torch.Size([1, 5])

In [31]:
features.shape

torch.Size([1, 5])

In [32]:
weights.view(5,1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [33]:
weights.shape

torch.Size([1, 5])

In [34]:
y = activation(torch.mm(features,weights.view(5,1)+bias))

In [35]:
y

tensor([[0.2154]])

### Stack layers of neurons

In [36]:
# Generate data
#set random seed
torch.manual_seed(7)

# create features with 3 random variables
features = torch.randn(1,3)

# define sizes for layers
n_input = features.shape[1] #input match shape of features
n_hidden = 2 # hidden units
n_output = 1 # NN Output

# Weights for input to hidden
W1 = torch.randn(n_input, n_hidden)
# weights for hidden to output
W2 = torch.randn(n_hidden, n_output)

# Bias terms
B1 = torch.randn(1, n_hidden)
B2 = torch.randn(1, n_output)



In [40]:
# Calculate output for multi layer networks

#Calculate hidden layer
h = activation(torch.mm(features, W1)+B1)

# use hidden layer as input for output layer
output = activation(torch.mm(h, W2)+B2)

print(output)




tensor([[0.3171]])


In [41]:
### Convert between numpy and pytorch


In [42]:
import numpy as np

In [45]:
#Create random numpy Array
a = np.random.rand(4,3)

In [46]:
a

array([[ 0.69457384,  0.60498399,  0.75081946],
       [ 0.74859522,  0.89506734,  0.50415947],
       [ 0.68686611,  0.76736455,  0.60182847],
       [ 0.62783419,  0.30912305,  0.14196005]])

In [49]:
# convert to torch tensor
b = torch.from_numpy(a)

In [48]:
b

tensor([[0.6946, 0.6050, 0.7508],
        [0.7486, 0.8951, 0.5042],
        [0.6869, 0.7674, 0.6018],
        [0.6278, 0.3091, 0.1420]], dtype=torch.float64)

In [51]:

b.numpy()

array([[ 0.69457384,  0.60498399,  0.75081946],
       [ 0.74859522,  0.89506734,  0.50415947],
       [ 0.68686611,  0.76736455,  0.60182847],
       [ 0.62783419,  0.30912305,  0.14196005]])

In [52]:
#memor shared between numpy and torch tensor
b.mul_(2)

tensor([[1.3891, 1.2100, 1.5016],
        [1.4972, 1.7901, 1.0083],
        [1.3737, 1.5347, 1.2037],
        [1.2557, 0.6182, 0.2839]], dtype=torch.float64)

In [53]:
a

array([[ 1.38914768,  1.20996797,  1.50163892],
       [ 1.49719045,  1.79013468,  1.00831894],
       [ 1.37373222,  1.53472909,  1.20365695],
       [ 1.25566838,  0.6182461 ,  0.28392011]])